#!/usr/bin/bash

# oh-my-posh's directory
declare OMP_DIR="${HOME}/.config/oh-my-posh"
# oh-my-posh's themes directory
declare OMP_THEMES_DIR="${OMP_DIR}/themes"


function OhMyPoshSetTheme ()
{
    declare -r theme="$1"

    # private helper function
    function __ompSetTheme ()
    {
        eval "$(oh-my-posh init $(oh-my-posh get shell) --config $1)"
    }


    if [ -f ${theme} ]; then
        __ompSetTheme ${theme}

    elif [ -f ${OMP_THEMES_DIR}/${theme} ]; then
        __ompSetTheme ${OMP_THEMES_DIR}/${theme}

    elif [ -f ${OMP_THEMES_DIR}/${theme}.omp.json ]; then
        __ompSetTheme ${OMP_THEMES_DIR}/${theme}.omp.json

    else
        unset -f __ompSetTheme
        >&2 echo "Unable to find oh-my-posh's theme \"${theme}\""
        return 1
    fi


    unset -f __ompSetTheme
}


# nice omp themes:
#   - 1_shell
#   - amro
#   - lambda
#   - lambdageneration
#   - avit
#   - kali
#   - blue-owl
#   - onehalf.minimal
#   - spaceship
#   - tokyo
#   - emodipt
#   - grubvbox
#   - huvix
#   - markduiker
#   - material
#   - nordtron
#   - robbyrussel
#   - tiwahu


export OMP_PALETTE="solarizedDark"
OhMyPoshSetTheme "danieleln.minimal"
